package Views;

import Controllers.OrderController;
import Controllers.TenantController;
import core.View;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class OrderView extends javax.swing.JFrame {
    
    TenantController t = new TenantController();
    OrderController o = new OrderController();
    
    public OrderView() {
        initComponents();
        View.showData(t.getTenants(), restaurant);
        count.setEditable(false);
        count.setVisible(false);
        min.setVisible(false);
        plus.setVisible(false);
        mess.setVisible(false);
        tambahkan.setVisible(false);
        showSeats();
    }
    
    private void showSeats(){
        try {
            ResultSet a = this.o.seats();
            while(a.next()){
                meja.addItem(a.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void lostFocus(){
        count.setEditable(false);
        count.setVisible(false);
        min.setVisible(false);
        plus.setVisible(false);
        mess.setVisible(false);
        tambahkan.setVisible(false);
        restaurant.clearSelection();
        menu.clearSelection();
        keranjang.clearSelection();
    }
    
    public int countValue(){
        int res = 0;
        DefaultTableModel a = (DefaultTableModel)keranjang.getModel();
        for(int i = 0; i < a.getRowCount(); i++){
            if(
               restaurant.getValueAt(restaurant.getSelectedRow(), 1).equals(a.getValueAt(i, 1)) 
                    &&
               menu.getValueAt(menu.getSelectedRow(), 0) .equals(a.getValueAt(i, 2))
               )
            {
                res = Integer.valueOf((String)a.getValueAt(i, 3));
            }
        }
        return res;
    }

    
    public int isExist(String noTlp, String namaMakanan){
        int num = -1;
        for(int i = 0; i < keranjang.getRowCount(); i++){
            if(
                    keranjang.getValueAt(i, 2).equals(namaMakanan) &&
                    keranjang.getValueAt(i, 1).equals(noTlp)
              )
            {
                return i;
            }
        }
        return num;
    }
    
    public void updateTable(){
        DefaultTableModel dtm = (DefaultTableModel)keranjang.getModel();
        for(int i = 0; i < keranjang.getRowCount(); i++){
            if(
                    Integer.valueOf((String) keranjang.getValueAt(i, 3)) == 0
              )
            {
                dtm.removeRow(i);
            }
        }
    }
    
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        restaurant = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        plus = new javax.swing.JButton();
        min = new javax.swing.JButton();
        mess = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();
        lafjdsljafs = new javax.swing.JLabel();
        tambahkan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pesan = new javax.swing.JButton();
        meja = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    menu.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            menuMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(menu);

    restaurant.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    )
    {
        public boolean isCellEditable(int row, int column){
            return false;
        }
    }
    );
    restaurant.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            restaurantMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(restaurant);

    jLabel1.setText("Restaurant");

    jLabel2.setText("Menu");

    count.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    count.setText("0");

    plus.setText("+");
    plus.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plusActionPerformed(evt);
        }
    });

    min.setText("-");
    min.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            minActionPerformed(evt);
        }
    });

    mess.setText("Mau pesan berapa?");

    refresh.setText("Refresh");
    refresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            refreshActionPerformed(evt);
        }
    });

    keranjang.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Nama Tenant", "No. Telelpon", "Nama Menu", "Jumlah", "Harga"
        }
    ));
    keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            keranjangMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(keranjang);

    lafjdsljafs.setText("Keranjang");

    tambahkan.setText("Tambahkan");
    tambahkan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tambahkanActionPerformed(evt);
        }
    });

    jLabel3.setText("Buat pesanan?");

    pesan.setText("Pesan");
    pesan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            pesanActionPerformed(evt);
        }
    });

    jLabel4.setText("Meja");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(refresh))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(182, 182, 182)
                                    .addComponent(lafjdsljafs))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)))
                            .addGap(26, 26, 26))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(mess))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(min)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(plus))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(tambahkan)))
            .addContainerGap(20, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(back)
                .addComponent(refresh))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lafjdsljafs))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(mess)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(min)
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plus))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tambahkan))
                .addComponent(jLabel4))
            .addContainerGap(51, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new HomeView().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        count.setText(Integer.toString(countValue()));
        count.setEditable(true);
        count.setVisible(true);
        min.setVisible(true);
        plus.setVisible(true);
        mess.setVisible(true);
        tambahkan.setVisible(true);
    }//GEN-LAST:event_menuMouseClicked

    private void restaurantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantMouseClicked
        Object no_telp = restaurant.getValueAt(restaurant.getSelectedRow(), 1);
        ResultSet data = t.getTenantMenu((String) no_telp);
        View.refreshTable(menu);
        View.showData(data, menu);
    }//GEN-LAST:event_restaurantMouseClicked

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        int num = Integer.valueOf(count.getText());
        count.setText(Integer.toString(num+1));
    }//GEN-LAST:event_plusActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        int num = Integer.valueOf(count.getText());
        if(num==0){
            return;
        }
        count.setText(Integer.toString(num-1));
    }//GEN-LAST:event_minActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        this.lostFocus();
        View.refreshTable(menu);
    }//GEN-LAST:event_refreshActionPerformed

    private void keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keranjangMouseClicked
        // TODO add your handling code here:
        count.setText(String.valueOf(keranjang.getValueAt(keranjang.getSelectedRow(), 3)));
        count.setEditable(true);
        count.setVisible(true);
        min.setVisible(true);
        plus.setVisible(true);
        mess.setVisible(true);
        tambahkan.setVisible(true);
    }//GEN-LAST:event_keranjangMouseClicked

    private void tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanActionPerformed
        // TODO add your handling code here:
        if(keranjang.getRowCount()!= 0){
            pesan.setVisible(true);
        }
        DefaultTableModel dtm = (DefaultTableModel)keranjang.getModel();
        Object tenant, noTelp, namaMenu, hargaMenu, jml;
        if(keranjang.getSelectionModel().isSelectionEmpty()){
            tenant = (String) restaurant.getValueAt(restaurant.getSelectedRow(), 0);
            noTelp = (String) restaurant.getValueAt(restaurant.getSelectedRow(), 1);
            namaMenu = (String) menu.getValueAt(menu.getSelectedRow(), 0);
            hargaMenu = (int) menu.getValueAt(menu.getSelectedRow(), 1) * Integer.valueOf(count.getText());
            jml = count.getText();
        }
        else{
            tenant = (String) keranjang.getValueAt(keranjang.getSelectedRow(), 0);
            noTelp = (String) keranjang.getValueAt(keranjang.getSelectedRow(), 1);
            namaMenu = (String) keranjang.getValueAt(keranjang.getSelectedRow(), 2);
            hargaMenu = (int) keranjang.getValueAt(keranjang.getSelectedRow(), 4) * Integer.valueOf(count.getText());
            jml = count.getText();
        }
        if(isExist(String.valueOf(noTelp), String.valueOf(namaMenu))!= -1)
        {
            int i = isExist(String.valueOf(noTelp), String.valueOf(namaMenu));
            keranjang.setValueAt(count.getText(), i, 3);
            keranjang.setValueAt(Integer.valueOf(count.getText())*(int)keranjang.getValueAt(i, 4), i, 4);
        }
        else
        {
            Object[] data = {tenant, noTelp, namaMenu, jml, hargaMenu};
            dtm.addRow(data);
        }
        this.lostFocus();
        View.refreshTable(menu);
        this.updateTable();
    }//GEN-LAST:event_tambahkanActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        if(keranjang.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Isi menu yang ingin dipilih!");
            return;
        }
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        
        int totalHarga = 0;
        ArrayList<Object> nt = new ArrayList<>();
        for(int i = 0; i < keranjang.getRowCount(); i++){
            totalHarga += (Integer)keranjang.getValueAt(i, 4);
            if(!nt.contains(keranjang.getValueAt(i,1))){
                nt.add(keranjang.getValueAt(i,1));
            }
        }
        
        if((Integer)HomeView.auth[5] < totalHarga){
            JOptionPane.showMessageDialog(this, "Saldo tidak cukup!");
            return;
        }
        
        Object[] ntelp = nt.toArray();
        Object[] data = {HomeView.auth[0], meja.getSelectedItem(), totalHarga, dtf.format(now)};
        o.makeOrder(data);
        
        for (Object ntelp1 : ntelp) {
            Object[] tenantsData = {t.getTenantId(String.valueOf(ntelp1)), o.newestOrder()};
            o.makeTenantOrders(tenantsData);
        }
        
        for(int i = 0; i <keranjang.getRowCount(); i++){
            Object[] dataMenu = {o.newestOrder(), t.getIdMenu(String.valueOf(
                    keranjang.getValueAt(i, 1)), String.valueOf(keranjang.getValueAt(i, 2))),
                    keranjang.getValueAt(i,3)};
            o.addOrderMenu(dataMenu);
        }
        new HomeView().setVisible(true);
        dispose();
    }//GEN-LAST:event_pesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable keranjang;
    private javax.swing.JLabel lafjdsljafs;
    private javax.swing.JComboBox<String> meja;
    private javax.swing.JTable menu;
    private javax.swing.JLabel mess;
    private javax.swing.JButton min;
    private javax.swing.JButton pesan;
    private javax.swing.JButton plus;
    private javax.swing.JButton refresh;
    private javax.swing.JTable restaurant;
    private javax.swing.JButton tambahkan;
    // End of variables declaration//GEN-END:variables
}
